apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: down-node
  namespace: yawoen
spec:
  schedule: '17 20 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-management
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl 
              command:
                - /bin/sh
                - -c
                - kubectl scale deployment yawoen --replicas=0 --namespace=yawoen