---
# Service account the client will use to reset the deployment,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-management
  namespace: yawoen
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-management
  namespace: yawoen
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "deployments/scale"]
    resourceNames: ["yawoen"]
    verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
                                             # if you want to use `rollout status`
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-management
  namespace: yawoen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-management
subjects:
  - kind: ServiceAccount
    name: deployment-management
    namespace: yawoen